version: '3'

services:
  transfuser:
    build:
      context: ../common
      dockerfile: transfuser.dockerfile
      args:
        - CARLA_VERSION=${CARLA_VERSION}
        - TRANSFUSER_COMMIT=${TRANSFUSER_COMMIT}
    command: [
        "/bin/bash",
        "/scripts/train_multi.sh",
        "--root_dir", "${DATASET_PATH}",
        # "--epochs", "26",
        # "--schedule_reduce_epoch_01", "15",
        # "--schedule_reduce_epoch_02", "25",
        # "--load_file", "/logs/transfuser-2023-03-27_09-48-50/model_17.pth",
        # "--start_epoch", "17",
      ]
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./scripts:/scripts
      - ${DATASET_PATH}:${DATASET_PATH}
      - ${LOG_PATH:-./logs}:/logs
    restart: on-failure
    shm_size: 512M
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 2
              capabilities: [gpu]
