version: '3'

services:
  transfuser:
    build:
      context: .
      args:
        - CARLA_VERSION=${CARLA_VERSION}
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/transfuser/carla/PythonAPI:/transfuser/carla/PythonAPI/carla:/transfuser/carla/PythonAPI/carla/dist/carla-0.9.14-py3.7-linux-x86_64.egg:/transfuser/leaderboard:/transfuser/scenario_runner:/transfuser/team_code_transfuser
    volumes:
      - ./app:/app
      - ${DATASET_PATH:-./data}:/dataset
      - ${LOG_PATH:-./logs}:/logs
      - ${MODEL_PATH}:/model
    ports:
      - 8888:8888
    network_mode: host
    restart: on-failure
    shm_size: 512M
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 2
              capabilities: [gpu]
