version: '3'

services:
  carla:
    build:
      context: .
      dockerfile: carla-${CARLA_VERSION}.dockerfile
      args:
        - CARLA_IMAGE=${CARLA_IMAGE}
    restart: on-failure
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              device_ids: ["${GPU:-0}"]

  interfuser:
    build:
      context: .
      dockerfile: interfuser.dockerfile
      args:
        - CARLA_VERSION=${CARLA_VERSION}
        - INTERFUSER_COMMIT=${INTERFUSER_COMMIT}
    environment:
      - PYTHONUNBUFFERED=1
      # Specify which evaluation to run. The options are town05, 42routes and longest6
      - EVALUATION=${EVALUATION:-longest6}
      - ACTOR_AMOUNT=${ACTOR_AMOUNT:?Please set ACTOR_AMOUNT}
    volumes:
      - ${MODEL_PATH}:/interfuser/models
      - ${RESULT_PATH}:/interfuser/results
      - ${RESULT_PATH}/data:/interfuser/data
      - ./interfuser-extra:/extra
    command: /bin/bash /extra/run_evaluation.sh
    depends_on:
      carla:
        condition: service_healthy
    network_mode: service:carla
    restart: on-failure
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              device_ids: ["${GPU:-0}"]
