version: '3'

services:
  carla:
    build:
      context: .
      dockerfile: carla-${CARLA_VERSION}.dockerfile
      args:
        - CARLA_IMAGE=${CARLA_IMAGE:-carlasim/carla:${CARLA_VERSION}}
    restart: on-failure
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              device_ids: ["${GPU:-0}"]

  transfuser:
    build:
      context: .
      dockerfile: transfuser.dockerfile
      args:
        - CARLA_VERSION=${CARLA_VERSION}
        - TRANSFUSER_COMMIT=${TRANSFUSER_COMMIT}
    environment:
      PYTHONUNBUFFERED: "1"
      SAVE_PATH: "${SAVE_PATH-/results/viz}"
      ACTOR_AMOUNT: "${ACTOR_AMOUNT:?Please set ACTOR_AMOUNT}"
      TRANSFUSER_DAYTIME_HEADLIGHTS: "${TRANSFUSER_DAYTIME_HEADLIGHTS:-1}"
      # Specify which evaluation to run. The options are town05, 42routes and longest6
      EVALUATION: "${EVALUATION:-longest6}"
    volumes:
      - ${MODEL_PATH}:/model
      - ${RESULT_PATH}:/results
      - ./transfuser-extra:/extra
    command: /bin/bash /extra/local_evaluation.sh
    depends_on:
      carla:
        condition: service_healthy
    network_mode: service:carla
    restart: on-failure
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              device_ids: ["${GPU:-0}"]
