version: '3'

services:
  carla:
    build:
      context: ../../common
      dockerfile: carla-0.9.14.dockerfile
    restart: on-failure
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  routegen:
    build:
      context: src
      args:
        - CARLA_VERSION=0.9.14
    command: /bin/false
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./results/:/routegen/results
    depends_on:
      carla:
        condition: service_healthy
    network_mode: service:carla
    restart: on-failure
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
