version: '3'

services:
  carla:
    build:
      context: ../common
      dockerfile: carla-0.9.10.1.dockerfile
    restart: on-failure
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  prefuser:
    build:
      context: ../common
      dockerfile: transfuser.dockerfile
      args:
        - CARLA_VERSION=0.9.10.1
        - TRANSFUSER_COMMIT=2022
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./models/prefuser/:/transfuser/model_ckpt/transfuser
      - ./results/:/transfuser/results
    depends_on:
      carla:
        condition: service_healthy
    network_mode: service:carla
    restart: on-failure
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
